name: Delete User Data

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  delete-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run script
      env:
        SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
      run: npx tsx batch/index.ts
